# Generated by Django 3.0.4 on 2020-04-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.CharField(blank=True, max_length=30)),
                ('user', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(blank=True, help_text='Name should be Valid as per User Id', max_length=20)),
                ('description', models.TextField(help_text='Related Concern', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Instant Help',
            },
        ),
    ]
