# Generated by Django 3.0.4 on 2020-04-19 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instanthelp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='help',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
