# Generated by Django 3.0.4 on 2020-04-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanthelp', '0002_auto_20200419_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='subscriber',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
