# Generated by Django 3.0.4 on 2020-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanthelp', '0003_auto_20200419_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='subscriber',
            field=models.EmailField(blank=True, default='Student', max_length=30),
        ),
    ]
