# Generated by Django 3.0.4 on 2020-04-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique_for_date='created')),
                ('point1', models.CharField(blank=True, max_length=70)),
                ('point2', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, default='no', help_text='Minimum Resolution 1000X800 ')),
                ('created', models.DateField(auto_now_add=True)),
                ('concern', models.CharField(choices=[('Headline', 'Headline'), ('Alert', 'Alert'), ('Notification', 'Notification'), ('Students', 'Students'), ('Teachers', 'Teachers')], default='Headline', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
