# Generated by Django 3.0.4 on 2020-04-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='image',
            field=models.URLField(blank=True, help_text='Minimum Resolution 1000X800 '),
        ),
    ]
