# Generated by Django 3.0.4 on 2020-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200416_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
