# Generated by Django 3.0.4 on 2020-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200416_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Event Name should be Short', max_length=50)),
                ('date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
