# Generated by Django 3.0.4 on 2020-04-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_subscribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribe',
            new_name='subscription',
        ),
    ]
