# Generated by Django 3.0.4 on 2020-04-17 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200416_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
