# Generated by Django 3.0.4 on 2020-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_events_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
