# Generated by Django 3.0.4 on 2020-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_headlines_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, default='Mobile User', max_length=15),
        ),
    ]
