# Generated by Django 3.0.4 on 2020-04-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200419_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlines',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='headlines',
            name='point2',
        ),
        migrations.AlterField(
            model_name='headlines',
            name='concern',
            field=models.CharField(choices=[('Students', 'Students'), ('Teachers', 'Teachers'), ('Notification', 'Notification'), ('Alert', 'Alert'), ('Headline', 'Headline')], default='Students', help_text='For whom the Articles belongs to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='description',
            field=models.TextField(help_text='Short Description favourable Max Lenght 250 Characters', max_length=500),
        ),
    ]
